create or replace TABLE DB_CLEAR_STRATEGY.CZ_CLEAR_STRATEGY.DIM_AREA_OF_SHOT (
	ID_DIM_AREA_OF_SHOT NUMBER(18,0),
	AREA_OF_SHOT VARCHAR(16777216),
	LOAD_AT TIMESTAMP_NTZ(9)
);

create or replace TABLE DB_CLEAR_STRATEGY.CZ_CLEAR_STRATEGY.DIM_CALENDAR (
	"date" DATE,
	YEAR NUMBER(4,0),
	MONTH NUMBER(2,0),
	DAY NUMBER(2,0),
	SEASON VARCHAR(7),
	YEAR_QUARTER VARCHAR(7),
	QUARTER VARCHAR(2),
	WEEK_OF_YEAR NUMBER(2,0),
	DAY_OF_WEEK NUMBER(2,0),
	WEEKEND NUMBER(1,0)
);

create or replace TABLE DB_CLEAR_STRATEGY.CZ_CLEAR_STRATEGY.DIM_COMBINED_SHOT_TYPES (
	ID_DIM_COMBINED_SHOT_TYPE NUMBER(18,0),
	COMBINED_SHOT_TYPE VARCHAR(16777216),
	LOAD_AT TIMESTAMP_NTZ(9)
);

create or replace TABLE DB_CLEAR_STRATEGY.CZ_CLEAR_STRATEGY.DIM_RANGE_OF_SHOT (
	ID_DIM_RANGE_OF_SHOT NUMBER(18,0),
	RANGE_OF_SHOT VARCHAR(16777216),
	LOAD_AT TIMESTAMP_NTZ(9)
);

create or replace TABLE DB_CLEAR_STRATEGY.CZ_CLEAR_STRATEGY.DIM_SHOT_BASICS (
	ID_DIM_SHOT_BASICS NUMBER(18,0),
	SHOT_BASICS VARCHAR(16777216),
	LOAD_AT TIMESTAMP_NTZ(9)
);

create or replace TABLE DB_CLEAR_STRATEGY.CZ_CLEAR_STRATEGY.DIM_SHOT_TYPES (
	ID_DIM_SHOT_TYPES NUMBER(18,0),
	SHOT_TYPE VARCHAR(16777216),
	LOAD_AT TIMESTAMP_NTZ(9)
);

create or replace TABLE DB_CLEAR_STRATEGY.CZ_CLEAR_STRATEGY.DIM_TEAM (
	ID_DIM_TEAM NUMBER(18,0),
	TEAM_ID NUMBER(38,0),
	TEAM_NAME VARCHAR(16777216),
	LOAD_AT TIMESTAMP_NTZ(9)
);

create or replace TABLE DB_CLEAR_STRATEGY.CZ_CLEAR_STRATEGY.FT_MATCH (
	MATCH_ID NUMBER(38,0),
	GAME_SEASON VARCHAR(7),
	ID_DIM_TEAM NUMBER(1,0),
	DATE_OF_GAME DATE,
	ID_DIM_TEAM_HOME NUMBER(1,0),
	ID_DIM_TEAM_AWAY NUMBER(1,0),
	LAT_LNG VARCHAR(16777216),
	NUMBER_OF_SHOTS NUMBER(18,0),
	NUMBER_OF_GOALS NUMBER(38,0),
	LOAD_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9)
);

create or replace TABLE DB_CLEAR_STRATEGY.CZ_CLEAR_STRATEGY.FT_SHOTS (
	MATCH_ID NUMBER(38,0),
	SHOT_ID NUMBER(38,0),
	ID_DIM_SHOT_TYPE NUMBER(1,0),
	ID_DIM_COMBINED_SHOT_TYPE NUMBER(1,0),
	ID_DIM_TEAM NUMBER(1,0),
	ID_DIM_RANGE_OF_SHOT NUMBER(1,0),
	ID_DIM_SHOT_BASICS NUMBER(1,0),
	ID_DIM_AREA_OF_SHOT NUMBER(1,0),
	LOCATION_X NUMBER(38,0),
	LOCATION_Y NUMBER(38,0),
	REMAINING_MIN_INT NUMBER(38,0),
	REMAINING_MIN_FLOAT FLOAT,
	POWER_OF_SHOT_INT NUMBER(38,0),
	POWER_OF_SHOT_FLOAT FLOAT,
	REMAINING_SEC_INT NUMBER(38,0),
	REMAINING_SEC_FLOAT FLOAT,
	DISTANCE_OF_SHOT_INT NUMBER(38,0),
	DISTANCE_OF_SHOT_FLOAT FLOAT,
	IS_GOAL NUMBER(38,0),
	LOAD_AT TIMESTAMP_NTZ(9),
	UPDATED_AT TIMESTAMP_NTZ(9)
);